# Generated by Django 3.2.25 on 2024-06-27 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
            ],
            options={
                'verbose_name': 'E-Mail Emfpänger',
                'verbose_name_plural': 'E-Mail Emfpänger',
            },
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('-2', 'Lowest'), ('-1', 'Lower'), ('0', 'Normal'), ('1', 'High'), ('2', 'Emergency')], default='0', max_length=255, verbose_name='Priorität')),
                ('user', models.CharField(default='System', max_length=255, verbose_name='User')),
                ('category', models.CharField(choices=[('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('debug', 'DEBUG'), ('notset', 'NotSet'), ('fatal', 'FATAL'), ('task', 'TASK')], default='info', max_length=255, verbose_name='Kategorie')),
                ('reference', models.CharField(max_length=255, null=True, verbose_name='Referenz')),
                ('message', models.TextField(blank=True, max_length=65535, verbose_name='Message')),
                ('stack_trace', models.TextField(blank=True, max_length=65535, verbose_name='Stack Trace')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Logger',
                'verbose_name_plural': 'Logger',
            },
        ),
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_subject', models.CharField(blank=True, default='Fehlermeldung', max_length=255, verbose_name='Betreff in der E-Mail')),
                ('send_via_api', models.BooleanField(default=False, verbose_name='Send via API')),
                ('pushover_token', models.CharField(blank=True, max_length=255, verbose_name='Pushover Token')),
                ('pushover_user', models.CharField(blank=True, max_length=255, verbose_name='Pushover User')),
                ('pushover_retry', models.CharField(blank=True, default='60', max_length=255, verbose_name='Pushover Retry')),
                ('pushover_expire', models.CharField(blank=True, default='600', max_length=255, verbose_name='Pushover Expire')),
                ('error_mail', models.CharField(blank=True, max_length=255, verbose_name='Error E-Mail')),
                ('error_mail_password', models.CharField(blank=True, max_length=255, verbose_name='Error E-Mail Passwort')),
                ('error_mail_host', models.CharField(blank=True, default='smtp.strato.de', max_length=255, verbose_name='Error E-Mail Host')),
                ('error_mail_port', models.CharField(blank=True, default='465', max_length=255, verbose_name='Error E-Mail Port')),
            ],
            options={
                'verbose_name': 'Haupteinstellung',
                'verbose_name_plural': 'Haupteinstellungen',
            },
        ),
    ]
